
package CMS;

public class TicketSystem extends javax.swing.JFrame {

    /**
     * Creates new form TicketSystem
     */
    public TicketSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ticketList = new javax.swing.JButton();
        searchTicket = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        addTicket = new javax.swing.JButton();
        updateTicket = new javax.swing.JButton();
        deleteTicket = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ticketList.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        ticketList.setForeground(new java.awt.Color(0, 0, 102));
        ticketList.setText("Ticket List");
        ticketList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketListActionPerformed(evt);
            }
        });

        searchTicket.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        searchTicket.setForeground(new java.awt.Color(0, 0, 102));
        searchTicket.setText("Search Ticket");
        searchTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTicketActionPerformed(evt);
            }
        });

        Exit.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Exit.setForeground(new java.awt.Color(102, 102, 0));
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        addTicket.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        addTicket.setForeground(new java.awt.Color(0, 0, 102));
        addTicket.setText("Add Ticket");
        addTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTicketActionPerformed(evt);
            }
        });

        updateTicket.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        updateTicket.setForeground(new java.awt.Color(0, 0, 102));
        updateTicket.setText("Update Ticket");
        updateTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTicketActionPerformed(evt);
            }
        });

        deleteTicket.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        deleteTicket.setForeground(new java.awt.Color(0, 0, 102));
        deleteTicket.setText("Delete Ticket");
        deleteTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTicketActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ticket System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(deleteTicket, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ticketList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(updateTicket, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(searchTicket, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ticketList, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ticketListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketListActionPerformed

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicketList().setVisible(true);
            }
        });
        
    }//GEN-LAST:event_ticketListActionPerformed

    private void searchTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTicketActionPerformed

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchTicket().setVisible(true);
            }
        });
        
    }//GEN-LAST:event_searchTicketActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void addTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTicketActionPerformed

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTicket().setVisible(true);
            }
        });
        
    }//GEN-LAST:event_addTicketActionPerformed

    private void updateTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTicketActionPerformed

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateTicket().setVisible(true);
            }
        });
        
    }//GEN-LAST:event_updateTicketActionPerformed

    private void deleteTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTicketActionPerformed

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteTicket().setVisible(true);
            }
        });
        
    }//GEN-LAST:event_deleteTicketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicketSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton addTicket;
    private javax.swing.JButton deleteTicket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton searchTicket;
    private javax.swing.JButton ticketList;
    private javax.swing.JButton updateTicket;
    // End of variables declaration//GEN-END:variables
}
